// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkmobhbmgxwrpuucoykn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrbW9iaGJtZ3h3cnB1dWNveWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNTU3MDIsImV4cCI6MjA3NzkzMTcwMn0.L6oWewdao71-gX0HeL8fpdYtCr_5NUyl8RUtq7uOLfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});